"use client";

/**
 * Single-page AI diagnostics dashboard (design proposal §6 MVP):
 * Signal bar on top, incident feed left, diagnosis detail right,
 * page-level AI disclaimer as footer backstop.
 */

import SignalBar from "@/components/SignalBar";

const PAGE_DISCLAIMER =
  "Diagnoses are generated by an LLM based on historical pattern matching. " +
  "They are suggestions, not conclusions — validate against current logs/metrics before acting.";

export default function Home() {
  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col gap-4 p-4">
      <header className="flex items-baseline justify-between">
        <h1 className="text-lg font-semibold text-slate-100">
          StreamLens <span className="text-slate-400">/ AI Diagnostics</span>
        </h1>
        <span className="text-xs text-slate-500">
          GitHub events · Kafka · Parquet · DuckDB
        </span>
      </header>

      <SignalBar />

      <div className="grid flex-1 grid-cols-[minmax(260px,1fr)_2fr] gap-4">
        <section
          aria-label="Incident feed"
          className="rounded-lg border border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-500"
        >
          Incident feed — coming in the next commit.
        </section>
        <section
          aria-label="Diagnosis detail"
          className="rounded-lg border border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-500"
        >
          Diagnosis detail — coming in the next commit.
        </section>
      </div>

      <footer className="border-t border-slate-800 pt-3 text-center text-[11px] text-slate-500">
        {PAGE_DISCLAIMER}
      </footer>
    </main>
  );
}
