"use client";

/**
 * Single-page AI diagnostics dashboard (design proposal §6 MVP):
 * Signal bar on top, incident feed left (polls /anomalies), diagnosis
 * detail right (/diagnose/:id), page-level AI disclaimer as footer backstop.
 */

import { useCallback, useEffect, useState } from "react";
import {
  Anomaly,
  Diagnosis,
  fetchAnomalies,
  fetchDiagnosis,
} from "@/lib/api";
import SignalBar from "@/components/SignalBar";
import IncidentFeed from "@/components/IncidentFeed";
import DiagnosisPanel from "@/components/DiagnosisPanel";

const FEED_POLL_MS = 7000; // §1: 5-10s polling is indistinguishable from push in a demo

const PAGE_DISCLAIMER =
  "Diagnoses are generated by an LLM based on historical pattern matching. " +
  "They are suggestions, not conclusions — validate against current logs/metrics before acting.";

export default function Home() {
  const [anomalies, setAnomalies] = useState<Anomaly[]>([]);
  const [feedError, setFeedError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [diagnosis, setDiagnosis] = useState<Diagnosis | null>(null);
  const [diagnosisLoading, setDiagnosisLoading] = useState(false);
  const [diagnosisError, setDiagnosisError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    const load = () =>
      fetchAnomalies()
        .then((list) => {
          if (!active) return;
          setAnomalies(list);
          setFeedError(null);
        })
        .catch((err: Error) => active && setFeedError(err.message));
    load();
    const timer = setInterval(load, FEED_POLL_MS);
    return () => {
      active = false;
      clearInterval(timer);
    };
  }, []);

  const selectAnomaly = useCallback((anomalyId: string) => {
    setSelectedId(anomalyId);
    setDiagnosis(null);
    setDiagnosisError(null);
    setDiagnosisLoading(true);
    fetchDiagnosis(anomalyId)
      .then((d) => {
        setDiagnosis(d);
        setDiagnosisLoading(false);
      })
      .catch((err: Error) => {
        setDiagnosisError(`Diagnosis failed: ${err.message}`);
        setDiagnosisLoading(false);
      });
  }, []);

  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col gap-4 p-4">
      <header className="flex items-baseline justify-between">
        <h1 className="text-lg font-semibold text-slate-100">
          StreamLens <span className="text-slate-400">/ AI Diagnostics</span>
        </h1>
        <span className="text-xs text-slate-500">
          GitHub events · Kafka · Parquet · DuckDB
        </span>
      </header>

      <SignalBar />

      <div className="grid flex-1 grid-cols-[minmax(260px,1fr)_2fr] gap-4">
        <IncidentFeed
          anomalies={anomalies}
          selectedId={selectedId}
          onSelect={selectAnomaly}
          error={feedError}
        />
        <DiagnosisPanel
          diagnosis={diagnosis}
          loading={diagnosisLoading}
          error={diagnosisError}
        />
      </div>

      <footer className="border-t border-slate-800 pt-3 text-center text-[11px] text-slate-500">
        {PAGE_DISCLAIMER}
      </footer>
    </main>
  );
}
