"""
api/schemas.py — Pydantic response/request models for the AI diagnostic API

The response shapes mirror the §2 information architecture so the frontend
can render top-to-bottom without reshaping: severity first, AI-generated
content clearly fenced in `generated` (with its notice), the computed Tier 2
`outcome_estimate` alongside it, similar cases, then raw evidence last.
"""

from datetime import datetime

from pydantic import BaseModel

# Per-block trust caption for everything LLM-generated (proposal §4).
AI_NOTICE: str = "AI-generated · verify before acting"

# Page-level backstop disclaimer (proposal §4).
DISCLAIMER: str = (
    "Diagnoses are generated by an LLM based on historical pattern matching. "
    "They are suggestions, not conclusions — validate against current "
    "logs/metrics before acting."
)


class Anomaly(BaseModel):
    anomaly_id: str
    type: str
    title: str
    severity: str          # "high" | "medium" | "low"
    description: str | None
    metric: dict
    repo: str | None
    detected_at: datetime
    is_demo: bool


class SignalComponent(BaseModel):
    status: str            # "ok" | "warn" | "alert" | "unknown"

    model_config = {"extra": "allow"}  # metric details vary per component


class PipelineSignal(BaseModel):
    ci_stability: SignalComponent
    pr_velocity: SignalComponent
    commit_cadence: SignalComponent
    caption: str


class SimilarCase(BaseModel):
    case_id: str
    kind: str
    title: str
    url: str | None
    labels: list[str]
    similarity_band: str   # "high" | "medium" | "low" — never a percentage
    was_reverted: bool
    time_to_resolve_hours: float | None
    snippet: str | None


class OutcomeEstimate(BaseModel):
    """Tier 2 — computed by DuckDB, NOT AI-generated, no AI notice."""

    sample_size: int
    pr_count: int
    revert_rate: float | None
    avg_time_to_resolve_hours: float | None
    severity_labels: list[str]


class GeneratedContent(BaseModel):
    """The LLM's output — always shipped with its per-block notice."""

    summary: str
    suggested_actions: list[str]
    confidence: str        # "high" | "medium" | "low" — qualitative band
    ai_notice: str = AI_NOTICE


class DiagnosisMeta(BaseModel):
    llm_provider: str      # "anthropic" | "stub"
    llm_model: str | None
    embedding_provider: str
    generated_at: datetime
    disclaimer: str = DISCLAIMER


class Diagnosis(BaseModel):
    anomaly: Anomaly
    generated: GeneratedContent
    outcome_estimate: OutcomeEstimate
    similar_cases: list[SimilarCase]
    raw_evidence: list[str]
    meta: DiagnosisMeta


class QueryRequest(BaseModel):
    question: str


class QueryResponse(BaseModel):
    question: str
    generated: GeneratedContent
    outcome_estimate: OutcomeEstimate
    similar_cases: list[SimilarCase]
    raw_evidence: list[str]
    meta: DiagnosisMeta


class DemoAnomalyRequest(BaseModel):
    type: str = "ci_failure_spike"
